language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository

env:
  - TNOODLE_INSTALL_GWT=1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3
  - nvm install v8.4
  - nvm use v8.4
  - (cd git-tools; npm install -d)
script:
  - ./tmt lint -a
  - ./tmt make dist -p wca
  - ./tmt make check
  - (cd tnoodle-ui; yarn test)
