[versions]
kotlin = "1.9.21"
ktor = "2.3.7"
kotless = "0.1.6"
junit-jupiter = "5.10.1"
batik = "1.17"
itext7 = "8.0.2"
logback = "1.3.14"

nodejs = "20.10.0"

[libraries]
markdownj-core = { module = "org.markdownj:markdownj-core", version = "0.4" }
zip4j = { module = "net.lingala.zip4j:zip4j", version = "2.11.5" }
itextpdf = { module = "com.itextpdf:itextpdf", version = "5.5.13.3" }
itext7 = { module = "com.itextpdf:itext7-core", version.ref = "itext7" }
itext7-bc-adapter = { module = "com.itextpdf:bouncy-castle-adapter", version.ref = "itext7" }
batik-transcoder = { module = "org.apache.xmlgraphics:batik-transcoder", version.ref = "batik" }
batik-codec = { module = "org.apache.xmlgraphics:batik-codec", version.ref = "batik" }
snakeyaml = { module = "org.yaml:snakeyaml", version = "2.2" }
system-tray = { module = "com.dorkbox:SystemTray", version = "4.4" }
bouncycastle = { module = "org.bouncycastle:bcprov-jdk15on", version = "1.70" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.2" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.7.1" }
kotlinx-atomicfu-gradle = { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin", version = "0.23.1" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-servlet = { module = "io.ktor:ktor-server-servlet", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.10" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlin-argparser = { module = "com.xenomachina:kotlin-argparser", version = "2.0.7" }
proguard-gradle = { module = "com.guardsquare:proguard-gradle", version = "7.4.1" }
wca-i18n = { module = "com.github.thewca:wca_i18n", version = "0.4.3" }
google-appengine-gradle = { module = "com.google.cloud.tools:appengine-gradle-plugin", version = "2.5.0" }
google-cloud-storage = { module = "com.google.cloud:google-cloud-storage", version = "2.30.1" }
tnoodle-scrambles = { module = "org.worldcubeassociation.tnoodle:lib-scrambles", version = "0.19.0" }
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version = "3.14.0" }
kotless-ktor = { module = "io.kotless:ktor-lang", version.ref = "kotless" }
mockk = { module = "io.mockk:mockk", version = "1.13.8" }
eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version = "6.2.0.202206071550-r" }

[bundles]
batik = ["batik-transcoder", "batik-codec"]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
nodejs = { id = "com.github.node-gradle.node", version = "7.0.1" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dependency-versions = { id = "com.github.ben-manes.versions", version = "0.50.0" }
kotless = { id = "io.kotless", version.ref = "kotless" }

google-appengine = { id = "com.google.cloud.tools.appengine", version = "2.4.2" }
kotlinx-atomicfu = { id = "kotlinx-atomicfu" }
